apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-k8s
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/ISAWASHUN/go-k8s
    path: kubernetes
    targetRevision: main
  project: default
