apiVersion: v1
kind: Service
metadata:
  name: go-k8s
  labels:
    app: go-k8s
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: go-k8s
  type: LoadBalancer
